//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MudBase.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IS_PAUSED {
            get {
                return ((bool)(this["IS_PAUSED"]));
            }
            set {
                this["IS_PAUSED"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ATTACK_OUT_OF_COMBAT {
            get {
                return ((bool)(this["ATTACK_OUT_OF_COMBAT"]));
            }
            set {
                this["ATTACK_OUT_OF_COMBAT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool HEAL_OUT_OF_COMBAT {
            get {
                return ((bool)(this["HEAL_OUT_OF_COMBAT"]));
            }
            set {
                this["HEAL_OUT_OF_COMBAT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool COMBAT_ROUTINE_PRECOMBATBUFF {
            get {
                return ((bool)(this["COMBAT_ROUTINE_PRECOMBATBUFF"]));
            }
            set {
                this["COMBAT_ROUTINE_PRECOMBATBUFF"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool COMBAT_ROUTINE_HEAL {
            get {
                return ((bool)(this["COMBAT_ROUTINE_HEAL"]));
            }
            set {
                this["COMBAT_ROUTINE_HEAL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool COMBAT_ROUTINE_COMBATBUFF {
            get {
                return ((bool)(this["COMBAT_ROUTINE_COMBATBUFF"]));
            }
            set {
                this["COMBAT_ROUTINE_COMBATBUFF"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool COMBAT_ROUTINE_COMBAT {
            get {
                return ((bool)(this["COMBAT_ROUTINE_COMBAT"]));
            }
            set {
                this["COMBAT_ROUTINE_COMBAT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>Enter Mob Names Here...</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection TARGET_MOB_LIST {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["TARGET_MOB_LIST"]));
            }
            set {
                this["TARGET_MOB_LIST"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int SELECTED_TARGETING_MODE {
            get {
                return ((int)(this["SELECTED_TARGETING_MODE"]));
            }
            set {
                this["SELECTED_TARGETING_MODE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int HOTKEY_PAUSE_MODIFIER {
            get {
                return ((int)(this["HOTKEY_PAUSE_MODIFIER"]));
            }
            set {
                this["HOTKEY_PAUSE_MODIFIER"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("P")]
        public string HOTKEY_PAUSE {
            get {
                return ((string)(this["HOTKEY_PAUSE"]));
            }
            set {
                this["HOTKEY_PAUSE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("T")]
        public string HOTKEY_TARGET_MODE {
            get {
                return ((string)(this["HOTKEY_TARGET_MODE"]));
            }
            set {
                this["HOTKEY_TARGET_MODE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int HOTKEY_TARGET_MODE_MODIFIER {
            get {
                return ((int)(this["HOTKEY_TARGET_MODE_MODIFIER"]));
            }
            set {
                this["HOTKEY_TARGET_MODE_MODIFIER"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int SELECTED_TARGET_LIST_TYPE {
            get {
                return ((int)(this["SELECTED_TARGET_LIST_TYPE"]));
            }
            set {
                this["SELECTED_TARGET_LIST_TYPE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool EXECUTE_WHILE_MOVING {
            get {
                return ((bool)(this["EXECUTE_WHILE_MOVING"]));
            }
            set {
                this["EXECUTE_WHILE_MOVING"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("25")]
        public decimal TARGETING_DISTANCE {
            get {
                return ((decimal)(this["TARGETING_DISTANCE"]));
            }
            set {
                this["TARGETING_DISTANCE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AUTO_FACE_TARGET {
            get {
                return ((bool)(this["AUTO_FACE_TARGET"]));
            }
            set {
                this["AUTO_FACE_TARGET"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool MOVE_TO_TARGET {
            get {
                return ((bool)(this["MOVE_TO_TARGET"]));
            }
            set {
                this["MOVE_TO_TARGET"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public decimal MOVE_TARGET_RANGE {
            get {
                return ((decimal)(this["MOVE_TARGET_RANGE"]));
            }
            set {
                this["MOVE_TARGET_RANGE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int SELECTED_MOVE_TARGET {
            get {
                return ((int)(this["SELECTED_MOVE_TARGET"]));
            }
            set {
                this["SELECTED_MOVE_TARGET"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AUTO_SPRINT {
            get {
                return ((bool)(this["AUTO_SPRINT"]));
            }
            set {
                this["AUTO_SPRINT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool FLASH_MESSAGES {
            get {
                return ((bool)(this["FLASH_MESSAGES"]));
            }
            set {
                this["FLASH_MESSAGES"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ACTIVATE_FFXIV {
            get {
                return ((bool)(this["ACTIVATE_FFXIV"]));
            }
            set {
                this["ACTIVATE_FFXIV"] = value;
            }
        }
    }
}
