//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MudBase.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    public sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool COMBAT_ROUTINE_PAUSED {
            get {
                return ((bool)(this["COMBAT_ROUTINE_PAUSED"]));
            }
            set {
                this["COMBAT_ROUTINE_PAUSED"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool COMBAT_ROUTINE_ATTACK_OUT_OF_COMBAT {
            get {
                return ((bool)(this["COMBAT_ROUTINE_ATTACK_OUT_OF_COMBAT"]));
            }
            set {
                this["COMBAT_ROUTINE_ATTACK_OUT_OF_COMBAT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool COMBAT_ROUTINE_HEAL_OUT_OF_COMBAT {
            get {
                return ((bool)(this["COMBAT_ROUTINE_HEAL_OUT_OF_COMBAT"]));
            }
            set {
                this["COMBAT_ROUTINE_HEAL_OUT_OF_COMBAT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool COMBAT_ROUTINE_PRECOMBATBUFF {
            get {
                return ((bool)(this["COMBAT_ROUTINE_PRECOMBATBUFF"]));
            }
            set {
                this["COMBAT_ROUTINE_PRECOMBATBUFF"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool COMBAT_ROUTINE_HEAL {
            get {
                return ((bool)(this["COMBAT_ROUTINE_HEAL"]));
            }
            set {
                this["COMBAT_ROUTINE_HEAL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool COMBAT_ROUTINE_COMBATBUFF {
            get {
                return ((bool)(this["COMBAT_ROUTINE_COMBATBUFF"]));
            }
            set {
                this["COMBAT_ROUTINE_COMBATBUFF"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool COMBAT_ROUTINE_COMBAT {
            get {
                return ((bool)(this["COMBAT_ROUTINE_COMBAT"]));
            }
            set {
                this["COMBAT_ROUTINE_COMBAT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>Enter Mob Names Here...</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection MOBS_TO_TARGET {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["MOBS_TO_TARGET"]));
            }
            set {
                this["MOBS_TO_TARGET"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int SELECTED_TARGETING_MODE {
            get {
                return ((int)(this["SELECTED_TARGETING_MODE"]));
            }
            set {
                this["SELECTED_TARGETING_MODE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int HOTKEY_MODIFIER_PAUSE {
            get {
                return ((int)(this["HOTKEY_MODIFIER_PAUSE"]));
            }
            set {
                this["HOTKEY_MODIFIER_PAUSE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("P")]
        public string HOTKEY_PAUSE {
            get {
                return ((string)(this["HOTKEY_PAUSE"]));
            }
            set {
                this["HOTKEY_PAUSE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("T")]
        public string HOTKEY_TARGET_MODE {
            get {
                return ((string)(this["HOTKEY_TARGET_MODE"]));
            }
            set {
                this["HOTKEY_TARGET_MODE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int HOTKEY_MODIFIER_TARGET_MODE {
            get {
                return ((int)(this["HOTKEY_MODIFIER_TARGET_MODE"]));
            }
            set {
                this["HOTKEY_MODIFIER_TARGET_MODE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int SELECTED_TARGET_LIST_TYPE {
            get {
                return ((int)(this["SELECTED_TARGET_LIST_TYPE"]));
            }
            set {
                this["SELECTED_TARGET_LIST_TYPE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool COMBAT_ROUTINE_EXECUTE_WHILE_MOVING {
            get {
                return ((bool)(this["COMBAT_ROUTINE_EXECUTE_WHILE_MOVING"]));
            }
            set {
                this["COMBAT_ROUTINE_EXECUTE_WHILE_MOVING"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("25")]
        public decimal MAX_TARGET_DISTANCE {
            get {
                return ((decimal)(this["MAX_TARGET_DISTANCE"]));
            }
            set {
                this["MAX_TARGET_DISTANCE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AUTO_FACE_TARGET {
            get {
                return ((bool)(this["AUTO_FACE_TARGET"]));
            }
            set {
                this["AUTO_FACE_TARGET"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AUTO_MOVE_TO_TARGET {
            get {
                return ((bool)(this["AUTO_MOVE_TO_TARGET"]));
            }
            set {
                this["AUTO_MOVE_TO_TARGET"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public decimal AUTO_MOVE_TARGET_RANGE {
            get {
                return ((decimal)(this["AUTO_MOVE_TARGET_RANGE"]));
            }
            set {
                this["AUTO_MOVE_TARGET_RANGE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int SELECTED_MOVE_TARGET {
            get {
                return ((int)(this["SELECTED_MOVE_TARGET"]));
            }
            set {
                this["SELECTED_MOVE_TARGET"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AUTO_SPRINT {
            get {
                return ((bool)(this["AUTO_SPRINT"]));
            }
            set {
                this["AUTO_SPRINT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool UI_FLASH_MESSAGES {
            get {
                return ((bool)(this["UI_FLASH_MESSAGES"]));
            }
            set {
                this["UI_FLASH_MESSAGES"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool UI_ACTIVATE_FFXIV {
            get {
                return ((bool)(this["UI_ACTIVATE_FFXIV"]));
            }
            set {
                this["UI_ACTIVATE_FFXIV"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool UI_ALWAYS_ON_TOP {
            get {
                return ((bool)(this["UI_ALWAYS_ON_TOP"]));
            }
            set {
                this["UI_ALWAYS_ON_TOP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("M")]
        public string HOTKEY_TOGGLE_MOVEMENT {
            get {
                return ((string)(this["HOTKEY_TOGGLE_MOVEMENT"]));
            }
            set {
                this["HOTKEY_TOGGLE_MOVEMENT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Insert")]
        public string HOTKEY_ADD_REM_TARGET_LIST {
            get {
                return ((string)(this["HOTKEY_ADD_REM_TARGET_LIST"]));
            }
            set {
                this["HOTKEY_ADD_REM_TARGET_LIST"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int HOTKEY_MODIFIER_TOGGLE_MOVEMENT {
            get {
                return ((int)(this["HOTKEY_MODIFIER_TOGGLE_MOVEMENT"]));
            }
            set {
                this["HOTKEY_MODIFIER_TOGGLE_MOVEMENT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int HOTKEY_MODIFIER_ADD_TARGET_LIST {
            get {
                return ((int)(this["HOTKEY_MODIFIER_ADD_TARGET_LIST"]));
            }
            set {
                this["HOTKEY_MODIFIER_ADD_TARGET_LIST"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int HOTKEY_MODIFIER_REM_TARGET_LIST {
            get {
                return ((int)(this["HOTKEY_MODIFIER_REM_TARGET_LIST"]));
            }
            set {
                this["HOTKEY_MODIFIER_REM_TARGET_LIST"] = value;
            }
        }
    }
}
